speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/ECAPA-TDNN_LSTM/1969
iemocap_prepare - Preparation completed in previous run, skipping.
speechbrain.dataio.encoder - Load called, but CategoricalEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 340, in <module>
    emo_id_brain = EmoIdBrain(
  File "/data2/home/zhangyue/speechbrain/speechbrain/core.py", line 491, in __init__
    self.modules = torch.nn.ModuleDict(modules).to(self.device)
  File "/home/zhangyue/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/zhangyue/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/zhangyue/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/zhangyue/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 616, in _apply
    self._buffers[key] = fn(buf)
  File "/home/zhangyue/anaconda3/envs/sb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
